Repository codesquad-memeber-2020/signup-1, pull requests merged in 2020-03, with the labels that each got.

#23 [#20] Feat: Test DB 접속 설정 추가 및 Test DB로 접속하도록 변경
  BE/src/main/resources/application.properties
Labels: enhancement

#28 [#22] Chore : gitignore 파일 추가
  .gitignore
Labels: enhancement

#37 [#36] Feat: 테스트용 workflow 생성
  .github/workflows/test-workflow.yml
Labels: test

#39 [#36] Feat: heroku login을 하도록 workflow 수정
  .github/workflows/test-workflow.yml
Labels: test

#40 [#36] Feat: heroku api key의 secret 값을 HEROKU_API_TOKEN으로 수정
  .github/workflows/test-workflow.yml
Labels: bug

#41 [#36] Feat: heroku deploy 테스트용 step 작성
  .github/workflows/test-workflow.yml
Labels: enhancement

#42 [#36] Fix: heroku app을 생성하지 않고 push해서 app을 생성하고 application name을 지정
  .github/workflows/test-workflow.yml
Labels: bug

#44 [#36] Fix: docker image를 올리는 스크립트를 git subtree push를 이용하도록 수정
  .github/workflows/test-workflow.yml
Labels: enhancement

#45 [#36] Fix: git subtree 명령어에 force 옵션이 없어서, 제거
  .github/workflows/test-workflow.yml
Labels: bug

#46 [#36] Fix: heroku login 하는 부분이 필요해서 추가
  .github/workflows/test-workflow.yml
Labels: bug

#47 [#36] Fix: Login의 문제가 아니라 환경변수명이 잘못되어서 수정
  .github/workflows/test-workflow.yml
Labels: bug

#48 [#36] Fix: 예제와 동일하게 HEROKU_APP_NAME을 환경변수로 추출
  .github/workflows/test-workflow.yml
Labels: bug

#49 [#36] Fix: 오타 수정 codesqaud → codesquad
  .github/workflows/test-workflow.yml
Labels: bug

#50 [#19] Test: 데이터 베이스 접속 테스트 코드 작성
  BE/.idea/modules.xml
  BE/build.gradle
  BE/src/test/java/com/codesquad/team1/signup/dbconnection/DBConnectionTest.java
Labels: test

#51 [#13] 데이터 베이스 접속 정보 암호화
  BE/build.gradle
  BE/src/main/java/com/codesquad/team1/signup/config/JasyptConfig.java
  BE/src/main/resources/application.properties
Labels: enhancement

#53 [#2] Feat: HTML/CSS 작성, 개발환경 세팅
  FE/.gitignore
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/scss/common.scss
  FE/scss/main.scss
  FE/scss/reset.scss
  FE/scss/variables.scss
  FE/src/signup.html
  FE/src/signup.js
  FE/webpack.config.js
Labels: enhancement

#54 [#2] Fix: SCSS 뎁스 2단계로 제한
  FE/scss/common.scss
Labels: enhancement

#56 [#6] Feat: 중복 이메일 조회 WEB API 구현
  BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
  BE/src/main/java/com/codesquad/team1/signup/repository/UserRepository.java
Labels: enhancement

#59 [#58] Fix: 관심사 태그 레이아웃 수정
  FE/scss/common.scss
  FE/scss/variables.scss
  FE/src/signup.html
Labels: bug

#64 [#29] Feat: 팝업 레이어 UI 추가
  FE/scss/common.scss
  FE/scss/main.scss
  FE/scss/modal.scss
  FE/scss/toggle-class.scss
  FE/scss/variables.scss
  FE/src/signup.html
Labels: enhancement

#67 [#27] 로그인/메인 화면 UI
  FE/scss/common.scss
  FE/scss/home.scss
  FE/scss/login.scss
  FE/scss/main.scss
  FE/src/home.html
  FE/src/main.js
  FE/src/signin.html
  FE/src/signup.html
  FE/webpack.config.js
Labels: enhancement

#66 [#14] Feat: logback 로깅 설정
  BE/src/main/resources/application.properties
Labels: enhancement

#71 [#63] Docs: 작업한 내용 Document 업데이트
  BE/README.md
Labels: documentation

#79 [#72] 대소문자 구분하지 않는 버그
  BE/src/main/java/com/codesquad/team1/signup/repository/UserRepository.java
Labels: bug, enhancement

#83 [#73] Chore: 빌드 파일 수정
  .github/workflows/dev-workflow.yml
  .github/workflows/master-workflow.yml
  BE/README.md
Labels: enhancement

#82 [#9] Feat: 유저 생성 기능 구현
  BE/README.md
  BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
  BE/src/main/java/com/codesquad/team1/signup/repository/User.java
Labels: enhancement

#86 [#85] Fix: Auto Deploy 오류 수정
  .github/workflows/dev-workflow.yml
  .github/workflows/master-workflow.yml
Labels: bug

#94 [#21] Feat: 유효성 검증 중간 PR
  FE/package-lock.json
  FE/package.json
  FE/src/home.js
  FE/src/main.js
  FE/src/modules/constants.js
  FE/src/modules/inputFields.js
  FE/src/modules/server.js
  FE/src/modules/userData.js
  FE/src/modules/util.js
  FE/src/modules/validation.js
  FE/src/scss/common.scss
  FE/src/scss/home.scss
  FE/src/scss/main.scss
  FE/src/scss/modal.scss
  FE/src/scss/reset.scss
  FE/src/scss/signin.scss
  FE/src/scss/toggle-class.scss
  FE/src/scss/variables.scss
  FE/src/signin.js
  FE/src/signup.html
  FE/src/signup.js
  FE/webpack.config.js
Labels: Feature

#97 [#21] Feat: Select태그, 생년월일 유효성 검증
  FE/src/modules/fields.js
  FE/src/modules/server.js
  FE/src/modules/validation.js
Labels: Feature, wontfix

#98 [#92] Fix: 이메일 정규표현식에 문제가 있어 수정
  BE/src/main/java/com/codesquad/team1/signup/constants/ValidationConstants.java
Labels: bug

#103 [#101] 스프링 부트 cors 문제 구현 (테스트 필요)
  BE/src/main/java/com/codesquad/team1/signup/config/WebConfig.java
Labels: bug

#105 [#88] Feat: 회원가입시 관심사 데이터 추가
  BE/README.md
  BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
  BE/src/main/java/com/codesquad/team1/signup/repository/Interest.java
  BE/src/main/java/com/codesquad/team1/signup/repository/InterestRepository.java
  BE/src/main/java/com/codesquad/team1/signup/repository/User.java
Labels: enhancement

#106 [#100] 로그아웃 메소드 GET=>POST로 변경
  BE/src/main/java/com/codesquad/team1/signup/controller/ApiUserController.java
Labels: enhancement

#111 [#74] Feat: 배포환경 별 설정정보를 다르게 지정
  BE/src/main/resources/application-develop.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/application-master.properties
  BE/src/main/resources/application.properties
Labels: Feature

#112 [#110] Fix: 관심사가 여러개 저장되지 않는 문제 해결
  BE/src/main/java/com/codesquad/team1/signup/repository/User.java
Labels: bug

#117 [#109] Refactor: Custom Exception 구조 생성
  BE/src/main/java/com/codesquad/team1/signup/api/ApiUserController.java
  BE/src/main/java/com/codesquad/team1/signup/common/constants/ErrorMessages.java
  BE/src/main/java/com/codesquad/team1/signup/common/exception/BusinessException.java
  BE/src/main/java/com/codesquad/team1/signup/common/exception/ForbiddenException.java
  BE/src/main/java/com/codesquad/team1/signup/common/exception/UnauthorizedException.java
  BE/src/main/java/com/codesquad/team1/signup/common/exception/UserCreateParameterInvalidException.java
  BE/src/main/java/com/codesquad/team1/signup/domain/user/User.java
Labels: enhancement

#118 [#24] 관심사 칩 기능
  BE/src/main/resources/static/css/home.css
  BE/src/main/resources/static/css/index.css
  BE/src/main/resources/static/css/signin.css
  BE/src/main/resources/static/dist/index.bundle.js
  BE/src/main/resources/static/index.html
  FE/babel.config.js
  FE/build.sh
  FE/package-lock.json
  FE/package.json
  FE/src/modules/constants.js
  FE/src/modules/fields.js
  FE/src/modules/interestChip.js
  FE/src/modules/interestFocus.js
  FE/src/modules/main.js
  FE/src/modules/server.js
  FE/src/modules/util.js
  FE/src/modules/validation.js
  FE/src/scss/common.scss
  FE/src/scss/toggle-class.scss
  FE/src/signup.html
  FE/src/signup.js
  FE/webpack.config.js
Labels: Feature

#116 아이디 중복체크
  iOS/.gitignore
  iOS/SignUp/SignUp.xcodeproj/project.pbxproj
  iOS/SignUp/SignUp.xcodeproj/project.xcworkspace/xcuserdata/keunnalee.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SignUp/SignUp.xcodeproj/xcuserdata/keunnalee.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  iOS/SignUp/SignUp/Base.lproj/Main.storyboard
  iOS/SignUp/SignUp/Controller/UserInfoViewController.swift
  iOS/SignUp/SignUp/Model/IDTextFieldDelegate.swift
  iOS/SignUp/SignUp/Model/PasswordConfirmationTextFieldDelegate.swift
  iOS/SignUp/SignUp/Model/PasswordTextFieldDelegate.swift
  iOS/SignUp/SignUp/Model/UserInfo.swift
  iOS/SignUp/SignUp/SignUp.entitlements
  iOS/SignUp/SignUp/SignUpViewController.swift
  iOS/SignUp/SignUp/View/IDTextField.swift
  iOS/SignUp/SignUp/View/PasswordConfirmationTextField.swift
  iOS/SignUp/SignUp/View/PasswordTextField.swift
Labels: Feature

#122 Hotfix
  BE/src/main/resources/static/dist/index.bundle.js
  FE/src/modules/interestChip.js
  FE/src/modules/server.js
Labels: bug
